name: Deploy to IONOS via SFTP
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: home590889551.1and1-data.host # Your SFTP server address
          username: ${{ secrets.FTP_USERNAME }} # Your SFTP username
          password: ${{ secrets.FTP_PASSWORD }} # Your SFTP password
          port: 22 # Port for SFTP
          script: |
            sftp -b - ${{ secrets.FTP_USERNAME }}@home590889551.1and1-data.host <<EOF
              cd /actual/path/to/remote/directory # Replace with your actual remote directory
              put -r ./your-local-directory/* # Replace with your actual local directory
              quit
EOF
