name: Deploy to IONOS via SFTP
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: home590889551.1and1-data.host # Your SFTP server address
          username: ${{ secrets.FTP_USERNAME }} # Your SFTP username
          password: ${{ secrets.FTP_PASSWORD }} # Your SFTP password
          port: 22 # Port for SFTP
          script: |
            sftp -o StrictHostKeyChecking=no -P $PORT $USERNAME@$HOST <<EOF
              cd /path/to/remote/directory
              put -r ./*
              quit
            EOF
              envs:
                HOST: "home590889551.1and1-data.host"
                USERNAME: "${{ secrets.FTP_USERNAME }}"
                PASSWORD: "${{ secrets.FTP_PASSWORD }}"
                PORT: "22" # CORRECT: This is a string.
