name: Deploy to IONOS via SFTP
on:
  push:
    branches:
      - main # Or whatever branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.FTP_HOST }} # Or your IONOS host directly
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22 # Or your SFTP port
          script: |
            sftp -o StrictHostKeyChecking=no -P 22 u82142318@home123456789.1and1-data.host <<EOF
              cd /yvetteagyei.com # Replace with your target directory
              put -r ./*
              quit
            EOF
