name: Deploy to IONOS via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Print Working Directory
        run: pwd
      - name: List Directory Contents
        run: ls -la /home/runner/work/my-website/my-website #Replace with your actual path
      - name: Deploy via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: home590889551.1and1-data.host
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }} #Consider switching to ssh keys
          port: 22
          source: home/runner/work/my-website/my-website/
