name: Deploy to IONOS via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Print Working Directory
        run: pwd
      - name: List Directory Contents
        run: ls -la /home/runner/work/my-website/my-website #Replace with your actual path
      - name: deploy
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: home590889551.1and1-data.host
          port: 22
          user: ${{ secrets.FTP_USERNAME }}
          pass: ${{ secrets.FTP_PASSWORD }}
          localDir: './'
          remoteDir: '.'
          reverse: true
